DELETE http://localhost:3333/book/1f2c6f00-2602-465a-bff5-711d94e42779
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjBkZTcyMzFiLWU5OTQtNDFjNy1iYjE1LWNmMzQxY2U4MzRkNiIsIm5hbWUiOiJEYW5pZWwgU2lsdmEiLCJpYXQiOjE3ODIwOTY2MzcsImV4cCI6MTc4MjA5NzUzN30.gEz4J2lA699s-ZkJwzMybyshVweoEHr83AkxzXEtoAw

###
GET http://localhost:3333/book?limit=5&page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ijk5OTI1ZWJjLWViODktNDNhMy1hMTZkLTc5ZGJjMjM2NzI3ZiIsIm5hbWUiOiJEYW5pZWwgc2lsdmEiLCJpYXQiOjE3ODIwOTc5MDYsImV4cCI6MTc4MjA5ODgwNn0.47iZsArL0HNTseC6imzrTmWA-XHUqhvkOkOIK--H8dY

###
POST http://localhost:3333/login
Content-Type: application/json

{
    "email": "danielsilva@gmail.com",
    "password": "danielsilva"
}

###
POST http://localhost:3333/register
Content-Type: application/json

{
    "name": "Daniel silva",
    "email": "danielsilva@gmail.com",
    "password": "danielsilva"
}
